### ISSUE TITLE
indexOf preferred over lastIndexOf for finding fragment start?

### ISSUE THREAD

**Issue by newmediaworks** [xbib/net#1]
https://github.com/xbib/net/blob/98470dc6387ed6544d76c57dc63ffa9fa1da221e/net-url/src/main/java/org/xbib/net/URL.java#L1174

From what I read, RFC 3986 never defines # as invalid with a fragment.  Furthermore, it specifies that the first # begins the fragment.  Perhaps this should be `indexOf` instead of `lastIndexOf`?

https://tools.ietf.org/html/rfc3986#section-3.3

> The path is terminated **by the first** question mark ("?") or number sign ("#") character, or by the end of the URI.

Although in the wild, # used twice would be unexpected.

**Comment by aoindustries** [comment]
We'd like to add the following from RFC 3986 as well:

https://tools.ietf.org/html/rfc3986#section-3.5

> A fragment identifier component is indicated by the presence of a number sign ("#") character and terminated by the end of the URI.

**Comment by newmediaworks** [comment]
Nevermind, I think I found a disambiguating specification in HTML 5:

https://dev.w3.org/html5/spec-LC/urls.html#url-manipulation-and-creation

> ... NUMBER SIGN character (#) ... then append the percent-encoded form of the character

So there would never be a valid URL with more than one unescaped (#)
